### ISSUE TITLE
Bug when using CLibrary() on Windows Path [TO CLOSE]

### ISSUE THREAD

**Issue by LeoSebal** [albertz/pyclibrary#1]
[Edit] Sorry I just saw that this is a fork of the original project. I'm not using the fork, so this is in the wrong place and I don't know how to delete this issue

Hello albertez,

Thank you for this fantastic module. I think it made a task I had to do something in the lines of 4 times faster. Unfortunately, as thankful as I am for this module, I'm not here for that, but to report a bug.

I have noticed that, when using the function CLibrary on Windows, pyclibrary only manages to locate the DLL in a different folder than the cwd if the path provided is a string with only backward slashes (Windows style). I have tried many variations: string with a forward slash, many variations of the libpath.Path and the libpath.PurePath submodules, with no success. I ended up using libpath.Path and convert it to a string with the as_posix() argument, then replacing the forward slashes with backward slashes if we're on Windows... Which kinda works but, as you guess, is not clean.

Anyway, I would like to thank you again for this fantastic work. Let me know if you need any additional information.

**Comment by albertz** [comment]
No problem. I just was about to write that. :)
You might also interested in [PyCParser](https://github.com/albertz/PyCParser), which is actually written by me, with some similar functionality. But I did not test it on Windows.
